title: Under Development
description:
baseurl: ""
repository: breese/breese.github.io
url: "http://breese.github.io"
markdown: kramdown
excerpt_separator: <!--more-->
theme: minima
plugins:
  - jekyll-feed
exclude:
  - src
